module.exports = {
  STALL_SPEED_KMPH: Number(process.env.STALL_SPEED_KMPH || 3),
  STALL_MINUTES: Number(process.env.STALL_MINUTES || 5),
  STALL_REMARK_COOLDOWN_MINUTES: Number(process.env.STALL_REMARK_COOLDOWN_MINUTES || 10),
  GEOFENCE_RADIUS_METERS: Number(process.env.GEOFENCE_RADIUS_METERS || 100),
  CONVERSION_GRACE_MINUTES: Number(process.env.CONVERSION_GRACE_MINUTES || 3),
  ARRIVAL_NOTIFY_MINUTES: Number(process.env.ARRIVAL_NOTIFY_MINUTES || 5),
  JOB_INTERVAL_MS: Number(process.env.JOB_INTERVAL_MS || 30_000),
};
